[[redirects]]
from = "/*"
to = "https://asasmith.dev/:splat"
status = 301
force = true
conditions = { Host = ["asasmith.com", "www.asasmith.com"] }

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
