name: CI
on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Enable pnpm via corepack
        run: |
          corepack enable
          corepack prepare pnpm@8.15.4 --activate

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Type Check 
        run: pnpm tsc:check
